---

- name: Hosts
  gather_facts: no
  hosts: localhost

  tasks:

    - name: install the 'Development tools' package group
      yum:
        name: "@Development tools"
        state: present
      become: yes

    - name: add packages
      yum:
        name: "{{ item }}"
      with_items:
        - git
        - qemu-kvm
        - libvirt
        - virt-install
        - bridge-utils
        - libvirt-devel
        - libxslt-devel
        - libxml2-devel
        - libvirt-devel
        - libguestfs-tools-c
      become: yes

    - name: get url
      get_url:
        url: "https://releases.hashicorp.com/vagrant/1.9.4/vagrant_1.9.4_x86_64.rpm"
        dest: '/tmp/vagrant_1.9.4.rpm'
        validate_certs: no
      
    - name: install Vagrant
      yum:
        name: '/tmp/vagrant_1.9.4.rpm'
        state: present
      become: yes

    - name: install vagrant-libvirt plugin
      shell: 'vagrant plugin install vagrant-libvirt'
      #become: yes

    - name: install pips
      pip:
        name: "{{ item }}"
      with_items:
        - setuptools
        - ipaddress
        - pydotplus
        - jinja2
      become: yes

    - name: add user to libvirt group
      user:
        name: cumulus
        shell: /bin/bash
        groups: libvirt
        append: yes
      become: yes
    
    - name: start and enable libvritd process
      become: yes
      service: name=libvirtd enabled=yes state=started

